name: Build Windows Client

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.0"

      - name: Install Fyne dependencies
        run: |
          choco install -y mingw
          set CGO_ENABLED=1
          set CC=x86_64-w64-mingw32-gcc

      - name: Go mod tidy
        run: go mod tidy

      - name: Build .exe
        run: |
          go build -o SecondMonitor.exe main.go

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: SecondMonitor.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
